#! /bin/sh
# /etc/init.d/mtty

### BEGIN INIT INFO
# Provides:          mtty
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script to start mtty.sh
# Description:       Dumps output from tty to file
### END INIT INFO

# If you want a command to always run, put it here
DEV_PATHS="/dev/ttyUSB0 /dev/ttyUSB1 /dev/ttyUSB2/dev/ttyUSB3"
LOG_ROOT="/var/www/html"

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting mtty"
    for DEV_PATH in $DEV_PATHS; do
      DEV_NAME=$(basename $DEV_PATH)
      LOG_PATH="$LOG_ROOT/$DEV_NAME.log"
      mtty.sh $DEV_PATH $LOG_PATH &
    done
    ;;
  stop)
    echo "Stopping mtty"
      killall mtty.sh
    ;;
  *)
    echo "Usage: /etc/init.d/mtty {start|stop}"
    exit 1
    ;;
esac

exit 0
